"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Input = exports.Badge = exports.Avatar = exports.Table = exports.Text = exports.Space = exports.Button = void 0;
exports.Button = 'Button';
exports.Space = 'Space';
exports.Text = 'Text';
exports.Table = 'Table';
exports.Avatar = 'Avatar';
exports.Badge = 'Badge';
exports.Input = 'Input';
